// ItemImagePreviewBinding.java (generated by ViewBinding)
package com.example.bay.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;

import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;

import com.example.bay.R;

public final class ItemImagePreviewBinding implements ViewBinding {
    @NonNull
    private final View rootView;
    @NonNull
    public final ImageView ivRemove;
    @NonNull
    public final ImageView ivSelectedImage;

    private ItemImagePreviewBinding(@NonNull View rootView, @NonNull ImageView ivRemove,
                                    @NonNull ImageView ivSelectedImage) {
        this.rootView = rootView;
        this.ivRemove = ivRemove;
        this.ivSelectedImage = ivSelectedImage;
    }

    @NonNull
    public static ItemImagePreviewBinding inflate(@NonNull LayoutInflater inflater) {
        return inflate(inflater, null, false);
    }

    @NonNull
    public static ItemImagePreviewBinding inflate(@NonNull LayoutInflater inflater,
                                                  @NonNull ViewGroup parent, boolean attachToParent) {
        View root = inflater.inflate(R.layout.image_border_item_shopping, parent, false);
        if (attachToParent) {
            parent.addView(root);
        }
        return bind(root);
    }

    @NonNull
    public static ItemImagePreviewBinding bind(@NonNull View rootView) {
        int id;
        id = R.id.ivRemove;
        ImageView ivRemove = ViewBindings.findChildViewById(rootView, id);
        if (ivRemove == null) {
            throw new NullPointerException("Missing required view with ID: ".concat(rootView.getResources()
                    .getResourceName(id)));
        }
        id = R.id.ivSelectedImage;
        ImageView ivSelectedImage = ViewBindings.findChildViewById(rootView, id);
        if (ivSelectedImage == null) {
            throw new NullPointerException("Missing required view with ID: ".concat(rootView.getResources()
                    .getResourceName(id)));
        }
        return new ItemImagePreviewBinding(rootView, ivRemove, ivSelectedImage);
    }

    @NonNull
    @Override
    public View getRoot() {
        return rootView;
    }
}